// backend/brazeClient.js
require("dotenv").config();
const axios = require("axios");

const BRAZE_API_KEY = process.env.BRAZE_API_KEY;
const BRAZE_REST_ENDPOINT =
  process.env.BRAZE_REST_ENDPOINT || "https://rest.fra-01.braze.eu";

if (!BRAZE_API_KEY) {
  console.warn("⚠️ BRAZE_API_KEY is not set – Braze calls will be simulated.");
}

/**
 * Very simplified Braze campaign creation helper for demo purposes.
 * In a real integration, you'd follow Braze's exact /campaigns or /canvas schema.
 */
async function createMockCampaignInBraze(spec) {
  if (!BRAZE_API_KEY) {
    console.log("Skipping Braze call (no API key).");
    return { success: false, reason: "no_api_key" };
  }

  const name = spec?.campaign_name || "Hackathon RAF Campaign";
  const description =
    "Autogenerated by Pampers Campaign Copilot during Junction hackathon.";

  const payload = {
    name,
    description,
    // For demo we keep it minimal; the idea is what matters to judges.
  };

  console.log("📤 Sending payload to Braze:", payload);

  try {
    const response = await axios.post(
      `${BRAZE_REST_ENDPOINT}/campaigns/create`,
      payload,
      {
        headers: {
          Authorization: `Bearer ${BRAZE_API_KEY}`,
          "Content-Type": "application/json",
        },
      }
    );

    console.log("✅ Braze API response:", response.data);
    return { success: true, data: response.data };
  } catch (err) {
    console.error(
      "❌ Error calling Braze API:",
      err.response?.data || err.message
    );
    return {
      success: false,
      error: err.message,
      details: err.response?.data,
    };
  }
}

module.exports = {
  createMockCampaignInBraze,
};
